Repository DiegoArruda/soulpet-back, pull requests merged in 2023-05, with the labels that each got.

#46 Alteração produto
  database/database.js
  database/produto.js
  package-lock.json
  package.json
  routes/produtos.js
Labels: enhancement, bugfix

#47 Adição de else na rota de create agendamento
  routes/agendamentos.js
Labels: bugfix

#48 Dev
  database/database.js
  database/pedidos.js
  routes/pedidos.js
Labels: enhancement, bugfix

#49 Get produtos
  database/produto.js
  routes/produtos.js
Labels: enhancement

#50 Implementacao relatorio pdf
  package-lock.json
  package.json
  routes/clientes.js
Labels: enhancement

#51 Alteracoes get produtos
  routes/produtos.js
Labels: enhancement, bugfix

#53 Integrar delete produtos
  package-lock.json
  routes/produtos.js
Labels: bug, enhancement

#56 Paginacao pets
  routes/pets.js
Labels: enhancement

#57 Implementação do dashboard e suas rotas
  index.js
  package-lock.json
  routes/dashboard.js
Labels: enhancement

#58 Security
  .vscode/launch.json
  database/database.js
  index.js
  package-lock.json
  package.json
  routes/healthchecker.js
Labels: enhancement

#59 Put Produtos
  package-lock.json
  routes/pets.js
  routes/produtos.js
Labels: enhancement
