Repository DiegoArruda/soulpet-back, pull requests merged in 2023-04, with the labels that each got.

#29 Model Produtos
  database/produto.js
Labels: enhancement

#30 Implementação do model de serviço
  database/serviço.js
  package-lock.json
  package.json
Labels: documentation, enhancement

#31 Adicionando método post e sua rota. E corrigindo o model servico
  database/servico.js
  index.js
  routes/servicos.js
Labels: documentation, enhancement

#33 Post Produtos
  database/produto.js
  index.js
  routes/produtos.js
Labels: enhancement

#34 Rota Lista de agendamentos
  index.js
  routes/agendamentos.js
Labels: enhancement

#35 Adicionando método put e sua rota
  routes/servicos.js
Labels: documentation, enhancement

#36 Correção do model, alteração do campo preço de STRING para FLOAT
  database/servico.js
Labels: bugfix

#37 Rota post de agendamento (Pet_Servico)
  database/pet_servico.js
  routes/agendamentos.js
Labels: enhancement

#38 Pets servicos
  database/agendamento.js
Labels: documentation

#39 Correção do import do db Agendamento
  database/pet_servico.js
  routes/agendamentos.js
Labels: documentation

#40 Correção da exportação de agendamentp
  database/agendamento.js
Labels: documentation

#41 Correção de atributos de agendamento
  database/agendamento.js
  routes/agendamentos.js
Labels: documentation

#42 Fix da rota de agendamentos
  database/agendamento.js
  routes/agendamentos.js
Labels: bugfix

#43 Modelpedido
  database/pedido.js
  index.js
  routes/pedidos.js
Labels: enhancement

#44 Adicionando método get e sua rota
  routes/servicos.js
Labels: documentation, enhancement
